### ISSUE TITLE
What is the main reason sample is using a special document loader?

### ISSUE THREAD

**Issue by vongohren** [mattrglobal/jsonld-signatures-bbs#115]
Just trying to make sense on how this can be used in real live scenario and why this sample loads JSON from file? Which really lives live somewhere? Is it to keep test efficient and fast?

Would it work without that special loader, since jsonld will try to load urls?

**Comment by tplooker** [comment]
@vongohren good question, in general it is considered [best practise](https://w3c.github.io/json-ld-bp/#cache-context) to cache any remote context where possible. The document loader included in the sample is a simple way in which to do this.

> Would it work without that special loader, since jsonld will try to load urls?

Yes it does

**Comment by tplooker** [comment]
@vongohren anything else outstanding on this issue that needs to be clarified?

**Comment by vongohren** [comment]
@tplooker no sorry, thanks for the reply :D
