### ISSUE TITLE
bundle with src?

### ISSUE THREAD

**Issue by brianorwhatever** [mattrglobal/jsonld-signatures-bbs#121]
Is there anyway to bundle this with the src dir? debugging problems hits a brick wall when I land in here

**Comment by tplooker** [comment]
Hey @brianorwhatever im unsure what you mean by this, what environment are you trying to debug in?

**Comment by brianorwhatever** [comment]
Sorry, I managed to debug my issues no problem.. not sure why I was having troubles last night.

Found I had 2 problems with my code:
* credentialSubject didn't have an "id" value so was being dropped from the json-ld frame
* vc issuance was adding the wrong key id to the proof verificationMethod

Closing this issue now, thanks for the quick reply!

**Comment by kdenhartog** [comment]
>credentialSubject didn't have an "id" value so was being dropped from the json-ld frame

Yeah this is a common problem our team has had to deal with as well. I'm not really sure how to share these types of learnings more broadly. Any suggestions would be welcomed.

**Comment by brianorwhatever** [comment]
so @kdenhartog just to make sure I have this straight. Reading from this thread https://github.com/w3c-ccg/ldp-bbs2020/issues/45

- if the VC has an id it MUST be revealed
- the credentialSubject MUST have an id and be revealed

We are signing the compact form of the document, is that correct?
![image](https://user-images.githubusercontent.com/7122708/116505349-815b1b80-a86f-11eb-8ac8-ac83f8589d99.png)

**Comment by brianorwhatever** [comment]
nevermind, just read the spec - rdf normalized of course

**Comment by TimoGlastra** [comment]
> credentialSubject didn't have an "id" value so was being dropped from the json-ld frame

Could you elaborate on this one? I've had some trouble with `credentialSubject` values being dropped if I didn't specify a `type` in some cases. Is it related to this?
