### ISSUE TITLE
Update dependencies that are bringing in old versions of sodium-native which aren't compatible with latest node versions on Mac

### ISSUE THREAD

**Issue by kdenhartog** [mattrglobal/jsonld-signatures-bbs#166]
It seems based on #165 that there's an issue that's been discovered for Mac platform when using node.js v14 and v16. We currently only test for Ubuntu platforms and didn't catch this in our CI pipeline.

We should update our crypto-ld dependencies which appear to be bringing in some (unused) crypto-ld suites in the version that we're using which include sodium-native as a dependency. I believe that if we update to the latest version of crypto-ld this should resolve the issue since the latest versions have split out the crypto suites into their own libraries which would remove sodium-native from our dependency tree and avoid the issue of this library not working on Node.js V16 on Mac.

**Comment by tplooker** [comment]
This issue is now resolved through removal of the dependency on crypto-ld.
