### ISSUE TITLE
Sample "leaking" correlatable identifiers?

### ISSUE THREAD

**Issue by about-code** [mattrglobal/jsonld-signatures-bbs#169]
Note: This is less an issue about BBS+ signatures but more about the story of Verifiable Credentials in general and the way it is presented in README.md (in this  [revision](https://github.com/mattrglobal/jsonld-signatures-bbs/blob/f935008ae2997f6c808f83b509647402bd3eb33f/README.md])).

The README states that **only givenName, familyName and gender** should become part of the *output document* (selective disclosure). Given this statement I was surprised to see other information like the credential's `identifier` as well as the `credentialSubject`'s DID becoming revealed, too, even though neither was part of the reveal document / JSON-LD frame. This is just an example but out of curiosity: if this were a serious system for registration cards, weren't these the kind of identifiers which enabled correlation among colluding verifiers, so IDs which ZKPs/proof documents should *not* include?

(I am new to this stuff so please don't trust my own understanding of the matter, so far. I might be plain wrong in my assumptions and yet feel in a state of easily mixing up a few things). Thanks in advance.

> The following is an example of a signed JSON-LD document featuring a BbsBlsSignature2020 type signature.
> 
> ~~~json 
> {
>   "@context": [
>     "https://www.w3.org/2018/credentials/v1",
>     "https://w3id.org/citizenship/v1",
>     "https://w3id.org/security/bbs/v1"
>   ],
>   "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
>   "type": ["VerifiableCredential", "PermanentResidentCard"],
>   "issuer": "did:example:489398593",
>   "identifier": "83627465",
>   "name": "Permanent Resident Card",
>   "description": "Government of Example Permanent Resident Card.",
>   "issuanceDate": "2019-12-03T12:19:52Z",
>   "expirationDate": "2029-12-03T12:19:52Z",
>   "credentialSubject": {
>     "id": "did:example:b34ca6cd37bbf23",
>     "type": ["PermanentResident", "Person"],
>     "givenName": "JOHN",
>     "familyName": "SMITH",
>     "gender": "Male",
>     "image": "data:image/png;base64,iVBORw0KGgokJggg==",
>     "residentSince": "2015-01-01",
>     "lprCategory": "C09",
>     "lprNumber": "999-999-999",
>     "commuterClassification": "C1",
>     "birthCountry": "Bahamas",
>     "birthDate": "1958-07-17"
>   },
>   "proof": {
>     "type": "BbsBlsSignature2020",
>     "created": "2020-04-26T04:21:07Z",
>     "verificationMethod": "did:example:489398593#test",
>     "proofPurpose": "assertionMethod",
>     "proofValue": "jx2VhjyZqUT91e2OhzweJA7G2u2UvmiDtIfmr+wUWNHWno+UOAh0FaNpM8Br+5j2JBkH981/nO1I7/9PFaRrng6NXu7vzDroKtuyj6nHGkMmGq4OMmBzIqRnG3ybin/Sxmu5YwqOxPMRsWH3H+2wSA=="
>   }
> }
> ~~~
>
> Whereby a zero knowledge proof disclosing **only givenName, familyName and gender** can be derived, from the above assertion using the following as the reveal document which is a JSON-LD frame.
> 
> ~~~json
> {
>   "@context": [
>     "https://www.w3.org/2018/credentials/v1",
>     "https://w3id.org/citizenship/v1",
>     "https://w3id.org/security/bbs/v1"
>   ],
>   "type": ["VerifiableCredential", "PermanentResidentCard"],
>   "credentialSubject": {
>     "type": ["PermanentResident", "Person"],
>     "@explicit": true,
>     "givenName": {},
>     "familyName": {},
>     "gender": {}
>   }
> }
> ~~~
> That gives rise to the output zero knowledge proof
> 
> ~~~json
> {
>   "@context": [
>     "https://www.w3.org/2018/credentials/v1",
>     "https://w3id.org/citizenship/v1",
>     "https://w3id.org/security/bbs/v1"
>   ],
>   "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
>   "type": ["PermanentResidentCard", "VerifiableCredential"],
>   "description": "Government of Example Permanent Resident Card.",
>   "identifier": "83627465",                                   <==== Correlatable identifier leaking?
>   "name": "Permanent Resident Card",
>   "credentialSubject": {
>     "id": "did:example:b34ca6cd37bbf23",                      <==== Correlatable identifier leaking?
>     "type": ["Person", "PermanentResident"],
>     "familyName": "SMITH",
>     "gender": "Male",
>     "givenName": "JOHN"
>   },
>   "expirationDate": "2029-12-03T12:19:52Z",
>   "issuanceDate": "2019-12-03T12:19:52Z",
>   "issuer": "did:example:489398593",
>   "proof": {
>     "type": "BbsBlsSignatureProof2020",
>     "created": "2020-05-25T23:07:10Z",
>     "verificationMethod": "did:example:489398593#test",
>     "proofPurpose": "assertionMethod",
>     "proofValue": "ABgA/4N3qygQRJlX3gmQOlJRGbO1KTXKQUmaN02xl+FiNZUDmGfa5OoKtg0RJ4wxxA08t3Vut61G/pq4yN0bygaFk5EJF6j7zFXmz9Vc7EdlDAvUkXqPaKA8inSBNv97HiZ1o5hIpoRnepW89p4JXPVrFi8XbDARSZpCg18GUuUMaPQLHKU82M/9l8tqqG1lKBOs+sRAAAAAdKRrRPj6zAz5LPZgDZJ0J2rNJjQI+JNYbV4AYEVwW37sxQ99aGGvmBk3DL0sod1V/gAAAAJMLYjmrb92zV087wO8UtFLwMj7qJuqV9VkMDghdrrc3BGtJuQgKx2GTrOb4CQxI1bf+iG0USjTktcjTlKv3X5spg3+ihOnyve0HnMWWggAW22j8b78jbl7lkYGJvzIXTzrVJ5KdYp3tXMDTAX7CLEXAAAACVY8oocA9Bz1w42F8Yv7UAPHv4pSvunXqndFOet3kWtzYHYEbO5gc42wPQtLmTtmqP6kUbQv6ruxzRmANulB8fUfy2jah/QeHKvsp907YDnSfo2wofRxa/vzsZnVriw0UmZnP0sYjbhmCkhoQZkxhqel3IkOF+H80wzvCKCl6eq5biEFMYA4bXpDX6Ap5/6WS5SSFaJRWxW+hpR/9EuQE11sGtk2W2Wn4eBrQUgVqYgPLI+U/ONaUJrh+GVJ/XXx7xxbAUf/NeQ/13AkTnYNn1fUdiOJ2oKl1lGr59udFq2tBBsyC3msTtQPYJS084355GRBur5jnzPNJ2W6Gu3ZqqQeRrVyw1gzdhVDNOE8KUm9OQ3AvCuxo8PHNrqzNvc6VA==",
>     "nonce": "37pdwue1a8FWLqgwCd0QJ0IJTFhp609KtxeCTWZGnfAVE+sOBDffYez+TY/bmVy+6z4="
>   }
> }
> ~~~

**Comment by kdenhartog-mattr** [comment]
This is one of the odd behaviors of JSON-LD frames where because the `@explicit` tag is not used at the top level and by default JSON-LD defaults to `@explicit` [being false](https://www.w3.org/TR/json-ld-framing/#explicit-inclusion-flag), that the additional base level terms get included.

In order to make sure that this doesn't happen you'll need to include the `"@explicit": true` at every level of the frame in order to properly selectively disclose the attributes requested.

Here's the frame you'd be looking for I'd think:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3id.org/security/bbs/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "@explicit": true,
  "credentialSubject": {
    "type": ["PermanentResident", "Person"],
    "@explicit": true,
    "givenName": {},
    "familyName": {},
    "gender": {}
  }
}
```

**Comment by about-code** [comment]
Thank you @kdenhartog-mattr. My first attempt went into the same direction. Indeed it fixes disclosure of `Permanent Resident Card`'s `identifier` (but only that). I have been trying to get rid of `credentialSubject`'s  `id` and `did: ...` value, as well.

The answer which I believe applies to that second part, is: it doesn't work. The attribute can't be prevented to be "revealed" using the given `@context`s. Instead [Section 7.3 "Identifier Based Correlation"](https://www.w3.org/TR/vc-data-model/#identifier-based-correlation) explains the requirements on the value the given `did:`:

> *If strong anti-correlation properties are a requirement in a verifiable credentials system, it is strongly advised that identifiers are either:*
> 
>   - *Bound to a single origin*
>   - *Single-use*
>   - *Not used at all, but instead replaced by short-lived, single-use bearer tokens.*
> 
>  Source:  [w3.org/tr/vc-data-model](https://www.w3.org/TR/vc-data-model/#identifier-based-correlation)

So *single-use* means **it should be generated uniquely *for every new presentation*** (while I believed it was permanent). Since *this* project is about signatures and proofs the *Signature-Based Correlation* part in the VC spec is certainly what matters more to this project, so thank you, anyway :rose:
