### ISSUE TITLE
Creating verifiable presentation with derivedProof with bbs+ suite

### ISSUE THREAD

**Issue by picardcapt1212** [mattrglobal/jsonld-signatures-bbs#182]
Hi, I'm using jsonld-signature-bbs library for selective disclosure :)

I tried to create verifiable presentation with `BbsBlsSignature2020`, `BbsBlsSignature2020Proof` and got below error.
```text
{
      "verified": false,
      "error": {
        "name": "VerificationError",
        "errors": [
          {
            "name": "Error",
            "message": "Could not verify any proofs; no proofs matched the required suite and purpose.",
            "stack": "Error: Could not verify any proofs; no proofs matched the required suite and purpose.\n    at ProofSet.verify (/Users/ibct/01_ibct/dev/bbs-handler/node_modules/jsonld-signatures/lib/ProofSet.js:257:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at Object.verify (/Users/ibct/01_ibct/dev/bbs-handler/node_modules/jsonld-signatures/lib/jsonld-signatures.js:38:18)\n    at Object.<anonymous> (/Users/ibct/01_ibct/dev/bbs-handler/src/test/vp/vp.verify.spec.ts:46:24)"
          }
        ]
      }
    }
}
```
 
I looked up jsonld-signatures-bbs __tests__ folder and found out the suite you were using was `Ed25519Signature2018`.

So my question is below.
1. `BbsBlsSignature2020` and `BbsBlsSignature2020Proof` is only used for verifiable credential, 
which means when creating verifiable presentation we should use `Ed25519Signature2018` or `EcdsaSecp256k1Signature2019` etc suite right? And the suite keys which is for verifying should be registered in did document?

Thank you!

**Comment by AlexMesser** [comment]
Had the same issue. My issue was with `jsonld-signatures` version - I used `v10.0.0`. After downgrading to `v5.0.1` proof was successfully validated.

**Comment by picardcapt1212** [comment]
Thanks! I will. try with version 5.0.1👍
