### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by yuejun92** [mattrglobal/jsonld-signatures-bbs#199]
There are 2 High and 6 Medium findings came from **node-forge** and **xmldom**. Is it possible to up the version for the 2 libraries?
![security_findings](https://user-images.githubusercontent.com/12484773/188814185-53e3c018-70f4-4ce2-a062-f604154a1819.jpeg)

**Comment by tplooker** [comment]
@yuejun92 can you clarify where this has been produced from and what version of the library was used to produce this report, because there has been a bunch of dependency updates recently.

**Comment by yuejun92** [comment]
Hi @tplooker, this report is produced by [SNYK](https://snyk.io/) using v7.0.0. Upgrading the node-forge library to v1.3.0 will fix all the vulnerabilities. 
![h1](https://user-images.githubusercontent.com/12484773/190217075-a14c8e42-67d0-4f97-a951-4d57f71d0d3c.JPG)
![m1](https://user-images.githubusercontent.com/12484773/190217079-8b60cf21-f1fd-416b-91bc-23da9f4123e1.JPG)
![m2](https://user-images.githubusercontent.com/12484773/190217081-8c590709-7fff-476a-8458-b771cb1f1648.JPG)
![m3](https://user-images.githubusercontent.com/12484773/190217083-c8aef1ee-3bd9-438c-9052-5fef31353a0a.JPG)
![m4](https://user-images.githubusercontent.com/12484773/190217084-96643ffa-9377-4622-ab36-dde7a8ddedfe.JPG)

**Comment by tplooker** [comment]
@yuejun92 See [here](https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/yarn.lock#L3958-L3961) please update your targeted version of jsonld-signatures-bbs the latest release is [v1.1.0](https://github.com/mattrglobal/jsonld-signatures-bbs/releases/tag/1.1.0)

**Comment by tplooker** [comment]
This issue has been fixed in the latest release, closing as resolved.
