### ISSUE TITLE
SNYK vulnerabilities for V1.1.0

### ISSUE THREAD

**Issue by yuejun92** [mattrglobal/jsonld-signatures-bbs#202]
Hi,
Currently @mattrglobal/jsonld-signatures-bbs@1.1.0 is still using jsonld-signatures@5.0.1
There are 2High 6Medium flagged out in SNYK caused by the out-updated version of jsonld-signatures@5.0.1.
Is it possible to up the version for jsonId-signatures and jsonld?

Thank you.

![snyk-1](https://user-images.githubusercontent.com/12484773/192705454-5bf9e475-dd8f-43b3-a5ae-3f4e5af9f27e.png)
![snyk-2](https://user-images.githubusercontent.com/12484773/192705475-44c01830-fb5b-4495-b824-d63f47cbd384.png)

**Comment by yuejun92** [comment]
Hi, is there any updates?

**Comment by tplooker** [comment]
Issue is now addressed in [v1.1.2](https://github.com/mattrglobal/jsonld-signatures-bbs/releases/tag/v1.1.2)
