### ISSUE TITLE
JSON-LD Context for BBS+ Signatures has disappeared -- what should be used?

### ISSUE THREAD

**Issue by swcurran** [mattrglobal/jsonld-signatures-bbs#220]
The BBS+ Context for JSON-LD credentials seems to have disappeared.  The context https://w3id.org/security/bbs/v1 redirects to https://w3c-ccg.github.io/ldp-bbs2020/contexts/v1/ which returns a 404.  This has happened in the last day or two.

This is breaking all of our tests, and presumably will break all of our tutorials.  Any production environments built on this that don't cache the file are presumably also broken.

Is it just us?  Likely not, since our tests run on GHActions, but I figured I should ask.

Is there a replacement that we should be using?

Should we read anything into the context disappearing?

**Comment by swcurran** [comment]
@andrewwhitehead @tplooker -- can you provide any guidance?

**Comment by swcurran** [comment]
Cause of the problem is that the spec that contains the context was renamed 3 days again, and so the redirection no longer works.

See this comments on the issue in the W3C spec -- https://github.com/w3c-ccg/vc-di-bbs/issues/71#issuecomment-1476811053

**Comment by tplooker** [comment]
Thanks @swcurran, issue is now resolved see [here](https://github.com/w3c-ccg/vc-di-bbs/issues/71#issuecomment-1476817373)
