### ISSUE TITLE
output a VerifiablePresentation instead of VerifiableCredential

### ISSUE THREAD

**Issue by Fak3** [mattrglobal/jsonld-signatures-bbs#42]
I have noticed that in the examples the output of a signing function is also a VerifiableCredential, but according to the vc spec shouldn't it be VerifiablePresentation instead?

**Comment by tplooker** [comment]
Hi Fak this library is a generic linked data proof library i.e you can use it to sign any JSON-LD document whether that document is a VC or not, therefore the output of the sign function does nothing more than attach the proof element to the document. If you were to plug this suite into [vc-js](https://github.com/digitalbazaar/vc-js) then you would get objects in the context of VC's enforced across that API.

**Comment by tplooker** [comment]
I hope that answers your question please re-open the issue if not
