### ISSUE TITLE
Migrate to using the security context v3 for the signature suite and key definitions

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/jsonld-signatures-bbs#68]
Once https://github.com/w3c-ccg/security-vocab/pull/53 is merged this can be addressed

**Comment by tplooker** [comment]
With this merged we can now proceed with updating this library to use the unstable version of the v3 vocab

**Comment by kdenhartog** [comment]
WIP branch to work off: https://github.com/mattrglobal/jsonld-signatures-bbs/compare/tl/update-to-security-v3

**Comment by tplooker** [comment]
Outstanding work on this is to update the samples in the repo including what is in the root readme to show the new context element.
