### ISSUE TITLE
Update samples and docs

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/jsonld-signatures-bbs#70]
With the latest pending release changes to the API warrants updating the samples and associated documentation

**Comment by tplooker** [comment]
Additionally rust should not be listed as a pre-req in the root readme.

**Comment by antonimmo** [comment]
Do you mean I installed Rust for nothing?

**Comment by tplooker** [comment]
Yes apologies, this was erroneous carry over from the underlying dependencies this library [depends on](https://github.com/mattrglobal/node-bbs-signatures), PR #72 resolves this.

**Comment by tplooker** [comment]
Sample update will be addressed after the latest release of this library is done.

**Comment by antonimmo** [comment]
Also, it would be nice to state that `yarn install --frozen-lockfile` works for some npm versions only. I tried with v14.5.0 but failed, so I found out (via [this comment](https://github.com/mattrglobal/jsonld-signatures-bbs/issues/35#issuecomment-621337374)) that it has to do with the node version. I switched to v10.13.0 and it worked.

**Comment by tplooker** [comment]
@antonimmo we are in the process of updating the docs now, with the latest version of this library now dependent on [bbs-signatures](https://github.com/mattrglobal/bbs-signatures) rather than directly on [node-bbs-signatures](https://github.com/mattrglobal/node-bbs-signatures) you should be able to use the library beyond node version 10 (including 14), but thanks for pointing this out we will be sure to address

**Comment by tplooker** [comment]
Sample has now been updated to v0.7.0
