### ISSUE TITLE
compatibility between did-key and bls keypair

### ISSUE THREAD

**Issue by mohamedrajhi** [mattrglobal/jsonld-signatures-bbs#71]
Hello , 

I'm working on your example published in the sample folder .
I want to replace the did example by a real decentralized identity , so i decided to use did-method-key-js ( https://github.com/digitalbazaar/did-method-key-js )
This is your keypair used in the exemple after adding the did keys :
![image](https://user-images.githubusercontent.com/40335054/89509785-0711d500-d7d0-11ea-92e6-2a4cc21cd45d.png)

I have some issues with that because i can't generate a did doc using Bls12381G2KeyPair , i have got this error : 
![image](https://user-images.githubusercontent.com/40335054/89513442-d7190080-d7d4-11ea-82d9-ee01e1d5d2bc.png)
do you have any idea to solve this issue ?

**Comment by tplooker** [comment]
Hi @mohamedrajhi yes correct the example is limited to an example based did at the moment, please try integrating in with this library https://github.com/transmute-industries/did-key.js/tree/master/packages/bls12381 if you are looking for a did key implementation for bls12381, @OR13 may be able to provide some more details.

**Comment by OR13** [comment]
@mohamedrajhi see these fixtures... https://github.com/transmute-industries/did-key.js/blob/master/packages/bls12381/src/__fixtures__/index.ts#L13

**Comment by mohamedrajhi** [comment]
Thanks for your responses but i can't solve my issues yet , 
I want to use KeyToDid  fonction ( it transforms a keypair to a Did Doc and publish it )  from did-method-key (https://github.com/digitalbazaar/did-method-key-js ) but it doesn't support bls12381 keypair.
look at the example below from ed25519 we can generate the did doc : 
`const {Ed25519KeyPair} = require('crypto-ld');
const {keyToDidDoc} = require('did-method-key').driver();

const edKey = await Ed25519KeyPair.generate();

keyToDidDoc(edKey);

// Returns a DID Document
`
I want to find something similar with bls keypair in order to create the did doc from my bls keypair and publish it so i can resolve it after using the did key
@OR13 your example is self generated , so I don't know how can I resolve the Did Document if i use your example !

**Comment by OR13** [comment]
@mohamedrajhi 

https://github.com/transmute-industries/did-key.js/blob/master/packages/bls12381/src/driver.ts#L3
https://github.com/transmute-industries/did-key.js/blob/master/packages/workbench/src/pages/home/Home.js#L62

**Comment by tplooker** [comment]
@mohamedrajhi I am going to close this issue as I believe @OR13 library solves the problem, please re-open if you disagree. In future after the latest release of this library we will add a sample showing the end to end integration.
