### ISSUE TITLE
Export types from package

### ISSUE THREAD

**Issue by tplooker** [mattrglobal/jsonld-signatures-bbs#77]
Some of the types this package defines are useful for consumers to have available in typescript environments such as [KeyPairSigner](https://github.com/mattrglobal/jsonld-signatures-bbs/blob/master/src/types/KeyPairSigner.ts), therefore this package should export these from the top level.

**Comment by kdenhartog** [comment]
@tplooker and @colinyip Is this issue fine to close now that #78 has been merged?

**Comment by tplooker** [comment]
Yeap
